# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

writeDTable <- function(path, data) {
    invisible(.Call('DataGraph_writeDTable', PACKAGE = 'DataGraph', path, data))
}

openDTable <- function(path) {
    invisible(.Call('DataGraph_openDTable', PACKAGE = 'DataGraph', path))
}

syncDTable <- function(path) {
    invisible(.Call('DataGraph_syncDTable', PACKAGE = 'DataGraph', path))
}

closeDTable <- function(path) {
    invisible(.Call('DataGraph_closeDTable', PACKAGE = 'DataGraph', path))
}

addDTable <- function(path, data) {
    invisible(.Call('DataGraph_addDTable', PACKAGE = 'DataGraph', path, data))
}

openDTBin <- function(path) {
    invisible(.Call('DataGraph_openDTBin', PACKAGE = 'DataGraph', path))
}

closeDTBin <- function(path) {
    invisible(.Call('DataGraph_closeDTBin', PACKAGE = 'DataGraph', path))
}

syncDTBin <- function(path) {
    invisible(.Call('DataGraph_syncDTBin', PACKAGE = 'DataGraph', path))
}

infoDTBin <- function(path = "") {
    invisible(.Call('DataGraph_infoDTBin', PACKAGE = 'DataGraph', path))
}

addDTBin <- function(path, name, data, time = NA_real_) {
    invisible(.Call('DataGraph_addDTBin', PACKAGE = 'DataGraph', path, name, data, time))
}

